---
- name: Force user to change password
  hosts: all
  gather_facts: no
  become: yes
  vars_prompt:
    - name: user
      prompt: User
  tasks:
    - name: Set password expiration to 0
      shell: chage -d 0 {{ user }}
